export const INCIDENT_TYPES = {
  'rat-live': { label: '活鼠目擊',   labelEn: 'Live rat',        icon: '🐀', color: '#E24B4A', bg: 'rgba(226,75,74,.12)',   text: '#A32D2D' },
  'rat-dead': { label: '死鼠發現',   labelEn: 'Dead rat',        icon: '💀', color: '#888780', bg: 'rgba(136,135,128,.14)', text: '#5F5E5A' },
  'poisoned': { label: '受毒動物',   labelEn: 'Poisoned animal', icon: '⚠️', color: '#BA7517', bg: 'rgba(186,117,23,.12)',  text: '#854F0B' },
  'nest':     { label: '鼠巢/鼠洞', labelEn: 'Nest / burrow',   icon: '🕳️', color: '#185FA5', bg: 'rgba(24,95,165,.12)',   text: '#0C447C' },
  'env-risk': { label: '環境風險點', labelEn: 'Env. risk site',  icon: '📍', color: '#3B6D11', bg: 'rgba(59,109,17,.12)',   text: '#27500A' },
};

export const LOCATION_TYPES = {
  market:     { label: '傳統市場',     icon: '🏪' },
  restaurant: { label: '餐廳/夜市',   icon: '🍜' },
  garbage:    { label: '垃圾收集點',   icon: '🗑️' },
  drain:      { label: '排水溝/地下道', icon: '🚇' },
  park:       { label: '公園/綠地',   icon: '🌳' },
  building:   { label: '老舊建築',     icon: '🏚️' },
  transit:    { label: '捷運/交通',   icon: '🚇' },
  other:      { label: '其他',         icon: '📌' },
};

export const CAT_STATUS = {
  active:    { label: '活躍健康',   color: '#27500A', bg: 'rgba(59,109,17,.10)' },
  tnr:       { label: '已TNR絕育', color: '#0C447C', bg: 'rgba(24,95,165,.10)' },
  declining: { label: '數量減少',   color: '#854F0B', bg: 'rgba(186,117,23,.10)' },
  new:       { label: '新發現',     color: '#533AB7', bg: 'rgba(83,58,183,.10)' },
};

export const DRUG_BY = {
  gov:     '市政府/區公所',
  private: '私人/業主自行投放',
  unknown: '不明來源（自行發現）',
};

export const DRUG_COLOR = {
  blue:    '藍色藥餌',
  green:   '綠色藥餌',
  pink:    '粉紅藥餌',
  pellet:  '顆粒狀',
  station: '毒餌站（盒裝）',
  unknown: '外觀不明',
};

export const ANIMAL_TYPES = {
  cat:   '街貓',
  dog:   '流浪狗',
  bird:  '鳥類/猛禽',
  other: '其他動物',
};

export const DISTRICTS = [
  '士林區','內湖區','南港區','松山區',
  '北投區','中山區','信義區','大安區',
  '萬華區','中正區','文山區','大同區',
];

// ── Real data from news/social media (Apr 28 – May 4, 2026) ─────────────────
// Sources: 自由時報, 聯合報, 大紀元, ETtoday, 民視, Threads

export const SAMPLE_REPORTS = [
  {
    id: 1,
    type: 'rat-live',
    location: '中山區雙連市場花圃',
    district: '中山區',
    locType: 'market',
    desc: '白天發現10幾隻老鼠在花圃群聚，完全不怕人。網友：「這裡是14世紀的歐洲嗎？」（來源：Threads / 自由時報 2026-05-01）',
    count: '10+',
    time: '5月1日',
    x: 255, y: 118,
    source: '自由時報',
    sourceUrl: 'https://news.ltn.com.tw/news/life/breakingnews/5421743',
  },
  {
    id: 2,
    type: 'rat-live',
    location: '中山區心中山線形公園（雙連站至中山站）',
    district: '中山區',
    locType: 'park',
    desc: '線形公園多處鼠竄，鼠洞幾乎打通地底，整條公園老鼠逛大街。議員林亮君直播記錄。（來源：民視 / 聯合報 2026-05-01）',
    count: '10+',
    time: '5月1日',
    x: 270, y: 105,
    source: '民視新聞',
    sourceUrl: 'https://tw.news.yahoo.com/%E6%95%B4%E5%80%8B%E5%8C%97%E5%B8%82%E9%83%BD%E6%98%AF%E9%BC%A0%E6%A8%82%E5%9C%92',
  },
  {
    id: 3,
    type: 'rat-dead',
    location: '台北車站外圍人行道（中正區）',
    district: '中正區',
    locType: 'transit',
    desc: '醫師同事目擊死鼠陳屍北車外人行道，2隻鳥正在啄食鼠屍。台大婦產科施景中醫師臉書示警：「大家擔心的事情就快發生了」。（來源：自由時報 2026-05-03）',
    count: '1',
    animal: 'bird',
    time: '5月3日',
    x: 240, y: 195,
    source: '自由時報',
    sourceUrl: 'https://news.ltn.com.tw/news/life/breakingnews/5423999',
  },
  {
    id: 4,
    type: 'rat-live',
    location: '大安區（大安森林公園周邊）',
    district: '大安區',
    locType: 'park',
    desc: '大安區老鼠橫行，今年1月即爆發漢他病毒死亡病例（70餘歲男性，台灣26年來首例）。公園內鳳頭蒼鷹生態受到老鼠藥威脅。（來源：大紀元 / 自由時報 2026-05-03）',
    count: '6-10',
    time: '5月3日',
    x: 590, y: 122,
    source: '大紀元',
    sourceUrl: 'https://www.epochtimes.com/b5/26/5/3/n14755622.htm',
  },
  {
    id: 5,
    type: 'env-risk',
    location: '中山區心中山線形公園樹穴',
    district: '中山區',
    locType: 'park',
    desc: '市府在線形公園樹穴投放老鼠藥，未使用毒餌站，藥餌直接曝露於公共空間。醫師蔡依橙：美國此做法違法，誤食恐致器官出血衰竭。（來源：大紀元 2026-05-01）',
    count: '1',
    time: '5月1日',
    x: 262, y: 112,
    source: '大紀元',
    sourceUrl: 'https://www.epochtimes.com/b5/26/5/1/n14754383.htm',
  },
  {
    id: 6,
    type: 'rat-live',
    location: '松山區虎林街',
    district: '松山區',
    locType: 'other',
    desc: 'Threads網友留言：「今天在松山的虎林街也看到好幾隻很大隻的」。（來源：Threads / 自由時報 2026-05-01）',
    count: '2-5',
    time: '5月1日',
    x: 600, y: 80,
    source: 'Threads',
    sourceUrl: 'https://news.ltn.com.tw/news/life/breakingnews/5421743',
  },
  {
    id: 7,
    type: 'rat-live',
    location: '內湖區（木柵動物園周邊）',
    district: '內湖區',
    locType: 'park',
    desc: '動物園周邊鼠患嚴重，多次目擊老鼠出沒。（來源：聯合報 2026-05-03）',
    count: '6-10',
    time: '5月3日',
    x: 240, y: 42,
    source: '聯合報',
    sourceUrl: 'https://udn.com/news/story/124652/9478382',
  },
  {
    id: 8,
    type: 'poisoned',
    location: '中山區線形公園附近（毛小孩誤食通報）',
    district: '中山區',
    locType: 'park',
    desc: '有毛小孩誤食路邊老鼠藥後口吐白沫。議員林亮君記錄並質疑市府投藥方式。（來源：民視 2026-05-02）',
    count: '1',
    animal: 'dog',
    time: '5月2日',
    x: 268, y: 120,
    source: '民視新聞',
    sourceUrl: 'https://tw.news.yahoo.com/%E6%95%B4%E5%80%8B%E5%8C%97%E5%B8%82%E9%83%BD%E6%98%AF%E9%BC%A0%E6%A8%82%E5%9C%92',
  },
  {
    id: 9,
    type: 'rat-live',
    location: '士林區（雙連市場周邊延伸）',
    district: '士林區',
    locType: 'market',
    desc: '鼠患從中山雙連一帶蔓延至士林周邊市場區，市府已在基河路等處投藥。（來源：大紀元 2026-05-03）',
    count: '6-10',
    time: '5月3日',
    x: 80, y: 65,
    source: '大紀元',
    sourceUrl: 'https://www.epochtimes.com/b5/26/5/3/n14755622.htm',
  },
  {
    id: 10,
    type: 'env-risk',
    location: '全市47處公有市場（市場處公告）',
    district: '大同區',
    locType: 'market',
    desc: '台北市市場處宣布已完成47處公有市場、47處攤集場鼠餌投藥與噴藥清消。廚餘與食材殘渣管理仍是根本問題。（來源：大紀元 2026-05-03）',
    count: '10+',
    time: '5月3日',
    x: 570, y: 200,
    source: '大紀元',
    sourceUrl: 'https://www.epochtimes.com/b5/26/5/3/n14755622.htm',
  },
  {
    id: 11,
    type: 'rat-live',
    location: '文山區景美市場周邊',
    district: '文山區',
    locType: 'market',
    desc: '蔣萬安5月2日前往景美市場與民眾互動，現場有居民反映鼠患問題。（來源：聯合報 2026-05-02）',
    count: '2-5',
    time: '5月2日',
    x: 430, y: 215,
    source: '聯合報',
    sourceUrl: 'https://udn.com/news/story/124652/9477475',
  },
  {
    id: 12,
    type: 'nest',
    location: '中山區雙連市場附近地底',
    district: '中山區',
    locType: 'drain',
    desc: '雙連市場攤商表示，鼠洞幾乎已打通地底，整條線形公園下方是鼠窩。市府用發泡劑與碎石填補鼠洞。（來源：民視 2026-05-02）',
    count: '10+',
    time: '5月2日',
    x: 258, y: 125,
    source: '民視新聞',
  },
];

export const SAMPLE_CATS = [
  {
    id: 1,
    location: '中正區羅斯福路三段公園旁',
    district: '中正區',
    count: 6,
    status: 'tnr',
    names: '虎斑「小花」、橘貓「胖虎」、三花「阿妹」等6隻',
    desc: '已由里長協助TNR，活動範圍穩定。附近傳統市場後巷鼠患相對輕微，推測貓群有抑制作用。',
    ratNearby: 'no',
    caretaker: '黃里長',
    time: '1週前',
    x: 250, y: 195,
    photoUrl: null,
  },
  {
    id: 2,
    location: '大安區和平東路二段公園',
    district: '大安區',
    count: 4,
    status: 'active',
    names: '黑貓「小黑」、灰貓×2、白底橘紋母貓',
    desc: '活躍於公園角落與停車場，夜間巡邏廣。大安森林公園周邊雖有鼠患，但此貓群活動區塊相對安全。',
    ratNearby: 'yes',
    caretaker: '志工林女士',
    time: '3天前',
    x: 578, y: 132,
    photoUrl: null,
  },
  {
    id: 3,
    location: '萬華區西昌街（鄰近龍山寺）',
    district: '萬華區',
    count: 3,
    status: 'declining',
    names: '老虎紋母貓、幼貓×2',
    desc: '近期貓隻數量減少，疑似附近排水溝投藥導致。萬華區鼠患嚴重，貓群可能受波及。',
    ratNearby: 'yes',
    caretaker: null,
    time: '5天前',
    x: 98, y: 213,
    photoUrl: null,
  },
  {
    id: 4,
    location: '北投區公館路市場旁',
    district: '北投區',
    count: 5,
    status: 'active',
    names: '白貓「雪球」、橘白花貓×2、純橘×2',
    desc: '公園及老市場旁固定巡邏，里長反映近年鼠患明顯減少，認為貓群功不可沒。',
    ratNearby: 'no',
    caretaker: '貓咪協會北投站',
    time: '1週前',
    x: 92, y: 110,
    photoUrl: null,
  },
];

export const SAMPLE_DRUGS = [
  {
    id: 1,
    location: '中山區心中山線形公園樹穴（雙連站至中山站全段）',
    district: '中山區',
    date: '2026-05-01',
    timeStr: '09:00',
    by: 'gov',
    color: 'station',
    nearCat: 'unknown',
    desc: '台北市環保局在線形公園樹穴大量投放老鼠藥，部分未使用毒餌站，藥餌直接置於花圃。議員林亮君拍照公開批評，擔心兒童及寵物誤食。市府共已投放6,462公斤，緊急採購4,750公斤。（來源：聯合報 / 民視）',
    photoUrl: null,
    x: 260, y: 115,
    source: '聯合報',
    sourceUrl: 'https://udn.com/news/story/7323/9476214',
  },
  {
    id: 2,
    location: '全市47處公有市場及47處攤集場',
    district: '大同區',
    date: '2026-04-06',
    timeStr: '',
    by: 'gov',
    color: 'station',
    nearCat: 'unknown',
    desc: '台北市市場處完成47處公有市場、47處攤集場的鼠餌投藥及清消作業，防範漢他病毒擴散。（來源：大紀元 2026-05-03）',
    photoUrl: null,
    x: 570, y: 195,
    source: '大紀元',
    sourceUrl: 'https://www.epochtimes.com/b5/26/5/3/n14755622.htm',
  },
  {
    id: 3,
    location: '中山區雙連市場周邊鼠洞口',
    district: '中山區',
    date: '2026-05-02',
    timeStr: '08:00',
    by: 'gov',
    color: 'pellet',
    nearCat: 'yes',
    desc: '市府派員前往雙連市場投藥並以發泡劑填補鼠洞。台灣猛禽研究會警告：濫用老鼠藥恐培養出「超級老鼠」，天敵數量下降將使鼠患更嚴重。（來源：自由時報 2026-05-02）',
    photoUrl: null,
    x: 252, y: 122,
    source: '自由時報',
    sourceUrl: 'https://news.ltn.com.tw/news/life/breakingnews/5423286',
  },
  {
    id: 4,
    location: '大安區（大安森林公園附近）',
    district: '大安區',
    date: '2026-04-28',
    timeStr: '',
    by: 'gov',
    color: 'station',
    nearCat: 'yes',
    desc: '大安區投藥作業。議員何孟樺警告：中毒老鼠不會立即死亡，可能被大安森林公園的鳳頭蒼鷹捕食，威脅北市引以為傲的猛禽保育成果。（來源：自由時報 2026-05-03）',
    photoUrl: null,
    x: 582, y: 130,
    source: '自由時報',
    sourceUrl: 'https://news.ltn.com.tw/news/life/paper/1753369',
  },
];
